[platformio]
default_envs = esp32dev
extra_configs = platformio_override.ini

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/DHT sensor library@1.4.7
  bblanchon/ArduinoJson@7.4.3
build_flags =
  -D CORE_DEBUG_LEVEL=0
